SELECT
	OP.BATCH_ID
	, OP.SUB_EQUIP_CD
	, DR.ITEM_CD
	, DR.BARCODE2
	, SUM(DR.PICK_QTY) AS PICK_QTY
	, DR.STRR_ID
FROM
	MHE_DR DR
LEFT OUTER JOIN
	ORDER_PREPROCESSES OP
ON
	DR.WORK_UNIT = OP.BATCH_ID
AND
	DR.REF_NO = OP.CELL_ASSGN_CD
WHERE
	DR.WORK_UNIT = :batchId
AND
	OP.BATCH_ID = :batchId
GROUP BY 
	OP.BATCH_ID, OP.SUB_EQUIP_CD, DR.ITEM_CD, DR.BARCODE2, DR.STRR_ID