SELECT
	RACKS.CHUTE_NO, CELLS.CELL_CD, CELLS.CLASS_CD
FROM
	CELLS
LEFT OUTER JOIN
	RACKS
ON
	CELLS.EQUIP_CD = RACKS.RACK_CD
WHERE
	RACKS.CHUTE_NO IN ( :chuteNo )
AND
	RACKS.ACTIVE_FLAG = :activeFlag
AND
	CELLS.ACTIVE_FLAG = :activeFlag
AND
	(CELLS.CLASS_CD IS NULL OR CHAR_LENGTH(CELLS.CLASS_CD) = 0)
ORDER BY 
	CELLS.CELL_SEQ, CELLS.EQUIP_CD