SELECT 
	A.CHUTE_NO
	, A.REMAIN_CELL - COALESCE(B.SKU_CNT, 0) AS REMAIN_CELL
	, COALESCE(B.SKU_CNT, 0) AS SKU_CNT
	, COALESCE(B.PCS_CNT, 0) AS PCS_CNT
FROM (
SELECT
	RACKS.CHUTE_NO, COUNT(CELLS.cell_cd) - COUNT(CASE WHEN CHAR_LENGTH(CELLS.CLASS_CD) > 0 THEN 1 END ) AS remain_cell
FROM
	CELLS
LEFT OUTER JOIN
	RACKS
ON
	CELLS.EQUIP_CD = RACKS.RACK_CD
WHERE
	CHAR_LENGTH(RACKS.CHUTE_NO) > 0
AND
	RACKS.ACTIVE_FLAG = true
AND
	CELLS.ACTIVE_FLAG = true	
GROUP BY
	RACKS.CHUTE_NO
ORDER BY 
	RACKS.CHUTE_NO) A
left outer join 
(
	SELECT 
		SUB_EQUIP_CD AS CHUTE_NO, COUNT(CELL_ASSGN_CD) AS SKU_CNT, SUM(TOTAL_PCS) AS PCS_CNT 
	FROM 
		ORDER_PREPROCESSES 
	WHERE 
		BATCH_ID = :batchId
	GROUP BY 
		SUB_EQUIP_CD
)
B
ON
	A.CHUTE_NO = B.CHUTE_NO
ORDER BY 
	A.chute_no