SELECT 
	:domainId AS DOMAIN_ID
	, :batchId AS BATCH_ID
	, :jobType AS JOB_TYPE
	, 'FnF' AS COM_CD
	, 'REF_NO' AS CELL_ASSGN_TYPE
	, REF_NO AS CELL_ASSGN_CD
	, SHIPTO_NM AS CELL_ASSGN_NM
	, 'SORTER' AS EQUIP_TYPE
	, :equipCd AS EQUIP_CD
	, COUNT(distinct ITEM_CD) AS SKU_QTY
	, SUM(PICK_QTY) AS TOTAL_PCS
FROM 
	MHE_DR
WHERE 
	WORK_UNIT = :batchId
GROUP BY 
	REF_NO, SHIPTO_NM
ORDER BY
	SUM(PICK_QTY) DESC