SELECT 
	MD.ID, A.WH_CD, MD.STRR_ID, MD.STRR_NM
	, A.WORK_DATE, A.WORK_UNIT, A.BOX_NO
	, A.WAVE_NO, A.WORKSEQ_NO, A.OUTB_NO
	, MD.REF_NO, MD.SHIPTO_ID, MD.SHIPTO_NM
	, A.ITEM_CD, MD.ITEM_NM, MD.ITEM_SEASON
	, MD.ITEM_STYLE, MD.ITEM_COLOR, MD.ITEM_SIZE
	, MD.BARCODE, MD.PICK_QTY, A.CMPT_QTY, A.MHE_NO, MD.PACK_TCD
	, MDO.CELL_NO AS CELL_CD, MD.RFID_ITEM_YN
	, A.MHE_DATETIME, A.BOX_SEQ
	, :boxStatus AS STATUS, MD.OUTB_ECT_DATE, MD.BARCODE2, MD.OUTB_TCD
FROM 
	MHE_BOX A
LEFT OUTER JOIN
	MHE_DR MD
ON
	A.WORK_UNIT = MD.WORK_UNIT
AND
	A.SHIPTO_ID = MD.REF_NO
AND
	A.ITEM_CD = MD.ITEM_CD
LEFT OUTER JOIN
	MHE_DAS_ORDER MDO
ON
	A.WORK_UNIT = MDO.BATCH_NO
AND
	A.ITEM_CD = MDO.ITEM_CD
AND
	A.SHIPTO_ID = MDO.SHOP_CD
WHERE
	A.IF_YN <> :delYn
AND
	A.DEL_YN <> :delYn
AND
	A.WORK_UNIT = :batchId
AND
	MD.WORK_UNIT = :batchId
AND
	MDO.BATCH_NO = :batchId