-- DAS에서 WCS 오더정보를 가져갈때 이용하는 쿼리.
SELECT
	A.WH_CD AS SUSINCLA1 ,
	REPLACE(A.WORK_DATE, '-', '') AS ORDERDT ,
	A.STRR_ID AS BRANDCL ,
	A.STRR_NM AS BRANDNM ,
	A.WORK_UNIT AS PARTNO ,
	A.WAVE_NO AS SUSINCLA2 ,
	A.WORKSEQ_NO AS SUSINCLA3 ,
	A.OUTB_NO AS SUSINCLA4 ,
	A.OUTB_ECT_DATE AS ETC1 ,
	A.SHIPTO_ID AS CLIENTCD ,
	A.SHIPTO_NM AS CLIENTNM ,
	A.ADDR_1 AS ADDRESSNM ,
	A.ADDR_2 AS ADDDETAILNM ,
	A.ZIP_NO AS ZIPCOD ,
	A.TEL_NO AS TELNO ,
	CASE WHEN SHIPOWNER_CD = '2193'
	AND A.CARRIER_CD = 'YM' THEN '0004'
	WHEN SHIPOWNER_CD = '2192'
	AND A.CARRIER_CD = 'YM' THEN '0003'
	WHEN A.CARRIER_CD = 'S' THEN '0002'
	ELSE '0001' END AS ROUTECD ,
	A.COURSE_NM AS ROUTENM ,
	CASE WHEN A.CARRIER_CD = 'YM'
	OR A.CARRIER_CD = 'CJ' THEN A.CARRIER_CD
	WHEN A.CARRIER_CD = 'W' THEN 'CJ'
	WHEN A.CARRIER_CD = 'HJ' THEN 'HJ'
	ELSE 'S' END AS SLPCOD00 ,
	A.SHIPOWNER_CD AS SLPCOD01 ,
	A.COURSE_CD AS SLPCOD02 ,
	A.COURSE_NM AS SLPCOD03 ,
	A.ITEM_CD AS GOODSCD ,
	CASE WHEN SUBSTR(A.ITEM_NM,
	1,
	1) = '[' THEN A.ITEM_NM
	ELSE '[' || A.ITEM_CD || ']' || A.ITEM_NM END AS GOODSNM ,
	A.ITEM_SEASON AS SUSINCLA5 ,
	A.ITEM_STYLE AS STYLECD ,
	A.ITEM_COLOR AS COLORCD ,
	A.ITEM_SIZE AS INSIZECL ,
	A.BARCODE AS SCANCD ,
	G.SCANCODE01 AS SCANCD01 ,
	G.SCANCODE02 AS SCANCD02 ,
	A.MULTIPLY_QTY AS IPSUQT ,
	A.PICK_QTY AS SUSINQT ,
	A.CARRIER_CD AS SUSINCLA6 ,
	A.RFID_ITEM_YN AS SUSINCLA7
FROM
	MHE_DR A
LEFT JOIN (
	SELECT
		ITEM_CD,
		MAX(BARCODE) AS SCANCODE01,
		MAX(BARCODE2) AS SCANCODE02
	FROM
		MHE_ITEM_BARCODE_OPE2
	WHERE
		BRAND = 'I'
		AND (SUBSTR(BARCODE,
		1,
		2) = '88'
		OR SUBSTR(BARCODE2,
		1,
		2) = '88')
	GROUP BY
		ITEM_CD) G ON
	A.ITEM_CD = G.ITEM_CD
WHERE
	A.WORK_DATE = '20200720'
	AND A.WH_CD = 'ICF'
	AND A.STRR_ID = 'I'
	AND A.WORK_UNIT = '1001511264';