SELECT 
	MPO.JOB_DATE
	, MPO.BATCH_NO AS BATCH_ID
	, JB.TITLE
	, MPO.CHUTE_NO
	, DAS.CELL_NO
	, DAS.SHOP_CD
	, DAS.SHOP_NM
	, MPO.SKU_CD
	, MPO.SKU_BCD AS SKU_BARCD
	, SKU.BRAND_CD
	, SKU.SEASON_CD
	, SKU.STYLE_CD
	, SKU.COLOR_CD
	, SKU.SIZE_CD
	, MPO.ORDER_QTY
	, COALESCE(MPR.QTY, 0) AS PAS_QTY
	, COALESCE(DAS.CMPT_QTY, 0) AS DAS_QTY
	, COALESCE(MPR.QTY, 0) - COALESCE(DAS.CMPT_QTY, 0) AS DIFF_QTY
FROM 
	(
		SELECT 
			JOB_DATE, BATCH_NO, CHUTE_NO, SKU_CD, SKU_BCD, STRR_ID, SUM(ORDER_QTY) AS ORDER_QTY
	  	FROM 
	  		MHE_PAS_ORDER 
	  	WHERE 
	  		BATCH_NO in ( :batchList )
	  	GROUP BY 
	  		JOB_DATE, BATCH_NO, CHUTE_NO, SKU_CD, SKU_BCD, STRR_ID
	) AS MPO
LEFT OUTER JOIN
	(
		SELECT 
			BATCH_NO, JOB_TYPE, CHUTE_NO, SKU_CD, SKU_BCD, STRR_ID, SUM(QTY) AS QTY 
 		FROM 
 			MHE_PAS_RLST 
 		WHERE 
 			BATCH_NO in ( :batchList )
 		GROUP BY 
 			BATCH_NO, JOB_TYPE, CHUTE_NO, SKU_CD, SKU_BCD, STRR_ID
 	) AS MPR
ON
	MPO.BATCH_NO = MPR.BATCH_NO
AND 
	MPO.CHUTE_NO = MPR.CHUTE_NO
AND 
	MPO.SKU_CD = MPR.SKU_CD
AND 
	MPO.SKU_BCD = MPR.SKU_BCD
LEFT OUTER JOIN
	(
		SELECT 
			MDO.BATCH_NO, MDO.JOB_TYPE, MDO.CHUTE_NO
			, MDO.ITEM_CD, MDO.BARCODE, MDO.CELL_NO
			, MDO.SHOP_CD, MDO.SHOP_NM, MDO.STRR_ID
			, SUM(MDO.ORDER_QTY) AS DAS_ORDER_QTY
			, SUM(MD.CMPT_QTY) AS CMPT_QTY
		FROM 
			MHE_DAS_ORDER MDO
		LEFT OUTER JOIN
			MHE_DR MD
		ON
			MDO.BATCH_NO = MD.WORK_UNIT
		AND 
			MDO.ITEM_CD = MD.ITEM_CD
		AND 
			(MDO.SHOP_CD = MD.SHIPTO_ID or MDO.SHOP_CD = MD.REF_NO)
		WHERE 
			MD.WORK_UNIT in ( :batchList )
		AND 
			MDO.BATCH_NO in ( :batchList )
		GROUP BY 
			MDO.BATCH_NO, MDO.JOB_TYPE, MDO.CHUTE_NO
			, MDO.ITEM_CD, MDO.BARCODE, MDO.STRR_ID
			, MDO.CELL_NO, MDO.SHOP_CD, MDO.SHOP_NM
		ORDER BY MDO.BATCH_NO, MDO.CHUTE_NO, MDO.ITEM_CD
 	) AS DAS
ON
	MPO.CHUTE_NO = DAS.CHUTE_NO
AND 
	MPO.SKU_CD = DAS.ITEM_CD
LEFT OUTER JOIN
	JOB_BATCHES JB
ON
	MPO.BATCH_NO = JB.ID
LEFT OUTER JOIN
	SKU
ON
	MPO.SKU_CD = SKU.SKU_CD
WHERE
	MPO.BATCH_NO IN ( :batchList )
#if($cell_no)
AND DAS.CELL_NO LIKE :cell_no
#end
#if($shop_cd)
AND DAS.SHOP_CD LIKE :shop_cd
#end
#if($shop_nm)
AND DAS.SHOP_NM LIKE :shop_nm
#end
#if($sku_cd)
AND MPO.SKU_CD LIKE :sku_cd
#end
ORDER BY
	MPO.CHUTE_NO, MPO.SKU_CD