SELECT 
	 MDO.CHUTE_NO
	, MDO.ITEM_CD, MDO.CELL_NO
	, MDO.SHOP_CD, MDO.SHOP_NM
	, SUM(MDO.ORDER_QTY) AS ORDER_QTY
	, SUM(MD.CMPT_QTY) AS DAS_QTY
FROM 
	MHE_DAS_ORDER MDO
LEFT OUTER JOIN
	MHE_DR MD
ON
	MDO.BATCH_NO = MD.WORK_UNIT
AND 
	MDO.ITEM_CD = MD.ITEM_CD
AND 
	(MDO.SHOP_CD = MD.SHIPTO_ID or MDO.SHOP_CD = MD.REF_NO)
WHERE 
	MD.WORK_UNIT in ( :batchList )
AND 
	MDO.BATCH_NO in ( :batchList )
AND
	MDO.CHUTE_NO = :chute_no AND MDO.ITEM_CD = :sku_cd
GROUP BY 
	MDO.CHUTE_NO
	, MDO.ITEM_CD
	, MDO.CELL_NO, MDO.SHOP_CD, MDO.SHOP_NM