SELECT
	JB.JOB_DATE
	, JB.ID AS BATCH_ID
	, JB.TITLE
	, MPO.SHOP_CD
	, MPO.SHOP_NM
	, MPO.BOX_ID
	, MPO.CHUTE_NO
	, MDO.CELL_NO
	, MPO.SKU_CD
	, S.SKU_BARCD
	, MPO.ORDER_QTY
	, MPR.QTY AS PAS_QTY
FROM 
	MHE_PAS_ORDER MPO
LEFT OUTER JOIN
	(
		SELECT 
			BATCH_NO, CHUTE_NO, BOX_ID, SKU_CD, SUM(QTY) AS QTY 
		FROM 
			MHE_PAS_RLST 
		WHERE 
			BATCH_NO = :batchId 
		GROUP BY 
			BATCH_NO, CHUTE_NO, BOX_ID, SKU_CD
	) AS MPR
ON
	MPO.BATCH_NO = MPR.BATCH_NO
AND
	MPO.CHUTE_NO = MPR.CHUTE_NO
AND
	MPO.BOX_ID = MPR.BOX_ID
AND
	MPO.SKU_CD = MPR.SKU_CD
LEFT OUTER JOIN
	JOB_BATCHES JB
ON
	MPO.BATCH_NO = JB.ID
LEFT OUTER JOIN
	SKU S
ON
	MPO.SKU_CD = S.SKU_CD
AND
	S.DOMAIN_ID = :domainId
AND
	S.COM_CD = :comCd
LEFT OUTER JOIN
	MHE_DAS_ORDER MDO
ON
	MPO.BATCH_NO = MDO.BATCH_NO
AND 
	MPO.CHUTE_NO = MDO.CHUTE_NO
AND
	MPO.SKU_CD = MDO.ITEM_CD
LEFT OUTER JOIN
	(
		SELECT 
	 		BATCH_NO, ITEM_CD, SUM(CMPT_QTY) AS DAS_QTY
		FROM 
			MHE_DAS_RTN_BOX_RSLT 
		WHERE 
			BATCH_NO = :batchId
		GROUP BY 
			BATCH_NO, ITEM_CD
	) MDRBR
ON
	MPO.BATCH_NO = MDRBR.BATCH_NO
AND
	MPO.SKU_CD = MDRBR.ITEM_CD
WHERE 
	MPO.BATCH_NO = :batchId
AND 
	MPR.BATCH_NO = :batchId
#if($shop_nm)
AND MPO.SHOP_NM LIKE :shop_nm
#end
#if($cell_no)
AND MDO.CELL_NO LIKE :cell_no
#end
#if($sku_cd)
AND MPO.SKU_CD LIKE :sku_cd
#end
#if($box_id)
AND MPO.BOX_ID LIKE :box_id
#end
ORDER BY 
	MPO.CHUTE_NO, MDO.CELL_NO, MPO.BOX_ID