SELECT 
	MPO.JOB_DATE
	, MPO.BATCH_NO AS BATCH_ID
	, JB.TITLE
	, MPR.CHUTE_NO
	, MPO.SHOP_CD
	, MPO.SHOP_NM
	, MPO.BOX_ID
	, SKU.SKU_CD
	, MPR.SKU_BCD AS SKU_BARCD
	, SKU.BRAND_CD
	, SKU.SEASON_CD
	, SKU.STYLE_CD
	, SKU.COLOR_CD
	, SKU.SIZE_CD
	, MPR.DMG_QTY
	, MPR.NEW_QTY
FROM
MHE_PAS_RLST MPR
LEFT OUTER JOIN
	(
		SELECT 
			JOB_DATE, BATCH_NO, BOX_ID, SHOP_CD, SHOP_NM 
		FROM 
			MHE_PAS_ORDER 
		WHERE 
			BATCH_NO in ( :batchList )
		GROUP BY 
			JOB_DATE, BATCH_NO, BOX_ID, SHOP_CD, SHOP_NM
	) MPO
ON
	MPR.BATCH_NO = MPO.BATCH_NO
AND
	MPR.BOX_ID = MPO.BOX_ID
LEFT OUTER JOIN
	JOB_BATCHES JB
ON
	MPR.BATCH_NO = JB.ID
LEFT OUTER JOIN
	SKU
ON
	MPR.SKU_CD = SKU.SKU_CD
OR
	MPR.SKU_CD = SKU.SKU_BARCD
WHERE 
	MPR.BATCH_NO in ( :batchList )
AND 
	(MPR.NEW_QTY > 0 OR MPR.DMG_QTY > 0)
#if($shop_cd)
AND MPO.SHOP_CD LIKE :shop_cd
#end
#if($box_id)
AND MPO.BOX_ID LIKE :box_id
#end
#if($sku_cd)
AND (SKU.SKU_CD LIKE :sku_cd OR SKU.SKU_BARCD LIKE :sku_cd)
#end
ORDER BY 
	MPR.CHUTE_NO