SELECT 
	JB.ID AS BATCH_ID
	, JB.TITLE
	, JB.JOB_DATE
	, MPO.SHOP_CD
	, MPO.SHOP_NM
	, MPO.BOX_ID
	, MPO.CHUTE_NO
	, MPO.SKU_CD
	, S.SKU_NM
	, MPO.ORDER_QTY
	, MPR.QTY
FROM 
	MHE_PAS_ORDER MPO
LEFT OUTER JOIN
	MHE_PAS_RLST MPR
ON
	MPO.BATCH_NO = MPR.BATCH_NO
AND
	MPO.CHUTE_NO = MPR.CHUTE_NO
AND
	MPO.BOX_ID = MPR.BOX_ID
AND
	MPO.SKU_CD = MPR.SKU_CD
LEFT OUTER JOIN
	JOB_BATCHES JB
ON
	MPO.BATCH_NO = JB.ID
LEFT OUTER JOIN
	SKU S
ON
	MPO.SKU_CD = S.SKU_CD
AND
	SKU.DOMAIN_ID = :domainId
AND
	SKU.COM_CD = :comCd
WHERE 
	MPO.BATCH_NO = :batchId
AND 
	MPR.BATCH_NO = :batchId
#if($shop_cd)
AND MPO.SHOP_CD like :shop_cd
#end
#if($box_id)
AND MPO.BOX_ID like :box_id
#end
#if($chute_no)
AND MPO.CHUTE_NO = :chute_no
#end
#if($sku_cd)
AND MPO.SKU_CD like :sku_cd
#end
ORDER BY 
	MPO.CHUTE_NO