SELECT
	MDO.JOB_DATE
	, MDO.BATCH_NO AS BATCH_ID
	, JB.TITLE AS TITLE
	, MDO.CHUTE_NO
	, MDO.CELL_NO
	, MDRR.BOX_NO
	, MDRR.ITEM_CD AS SKU_CD
	, MDO.BARCODE AS SKU_BARCD
	, SKU.BRAND_CD
	, SKU.SEASON_CD
	, SKU.STYLE_CD
	, SKU.COLOR_CD
	, SKU.SIZE_CD
	, MDRR.CMPT_QTY AS PICKED_QTY
	, MDO.PLT_NO
	, MDRR.DEL_YN
FROM
	MHE_DAS_RTN_BOX_RSLT MDRR
LEFT OUTER JOIN
	MHE_DAS_ORDER MDO
ON
	MDRR.BATCH_NO = MDO.BATCH_NO
AND
	MDRR.ITEM_CD = MDO.ITEM_CD
LEFT OUTER JOIN
	JOB_BATCHES JB
ON
	MDRR.BATCH_NO = JB.ID
LEFT OUTER JOIN
	SKU SKU
ON
	MDRR.ITEM_CD = SKU.SKU_CD
AND
	SKU.DOMAIN_ID = :domainId
AND
	SKU.COM_CD = :comCd
WHERE
	MDRR.BATCH_NO = :batch_id
#if($cell_no)
AND MDO.CELL_NO LIKE :cell_no
#end
#if($box_id)
AND MDRR.BOX_NO like :box_id
#end
#if($sku_cd)
AND MDRR.ITEM_CD like :sku_cd
#end
ORDER BY
	MDO.CELL_NO