SELECT 
	HR.WORK_UNIT AS WMS_BATCH_NO
	, HR.WORK_UNIT AS WCS_BATCH_NO
	, 'FnF' AS COM_CD
	, 'A' AS AREA_CD
	, 'AB1' AS STAGE_CD
	, 'SDAS' AS JOB_TYPE
	, HR.WORKSEQ_NO AS JOB_SEQ
	, HR.DESCR AS MESSAGE
	, HR.STRR_ID AS BRAND_CD
	, 'SORTER' AS EQUIP_TYPE
	, :equipCd AS EQUIP_CD
	, 'order' AS ITEM_TYPE
	, 'W' AS STATUS
	, 0 AS SKIP_FLAG
	, (SELECT COUNT(*) FROM MHE_DR WHERE WH_CD = HR.WH_CD AND WORK_UNIT = HR.WORK_UNIT) AS TOTAL_RECORDS
	, (SELECT COUNT(DISTINCT(SHIPTO_ID)) FROM MHE_DR WHERE WH_CD = HR.WH_CD AND WORK_UNIT = HR.WORK_UNIT) AS TOTAL_ORDERS
	, (SELECT SUM(PICK_QTY) FROM MHE_DR WHERE WH_CD = HR.WH_CD AND WORK_UNIT = HR.WORK_UNIT) AS TOTAL_PCS
FROM 
	MHE_HR HR
WHERE
 	HR.WH_CD = :whCd
AND 
	HR.WORK_DATE = :jobDate
AND 
	HR.BIZ_TYPE = :bizType
AND 
	HR.STATUS = :status