SELECT
	:batchId AS BATCH_ID
	, :orderNo AS ORDER_NO
	, :wmsBatchNo AS WMS_BATCH_NO
	, :wcsBatchNo AS WCS_BATCH_NO
	, :jobDate AS JOB_DATE
	, DR.SEQ AS JOB_SEQ
	, 'SRTN' AS JOB_TYPE
	, :orderDate AS ORDER_DATE
	, 'FnF' AS COM_CD
	, 'A' AS AREA_CD
	, 'A-B1' AS STAGE_CD
	, 'SORTER' AS EQUIP_TYPE
	, DR.ITEM_CD AS SKU_CD
	, DR.BARCODE1 AS SKU_BARCD
	, DR.BARCODE2 AS SKU_BARCD2
	, SUM(TRG.INB_ECT_QTY) AS ORDER_QTY
	, DR.ITEM_GCD AS SKU_TYPE
FROM
	WCS_RTN_CHASU_SKU DR
LEFT OUTER JOIN
	(SELECT * FROM WMT_UIF_IMP_INB_RTN_TRG WHERE IF_CHK = 'N' AND WCS_IF_CHK = 'N') TRG
ON
	DR.ITEM_CD = TRG.REF_DETL_NO
AND
	DR.STRR_ID = TRG.STRR_ID
AND 
	DR.SEASON = TRG.REF_SEASON 
AND 
	DR.TYPE = TRG.SHOP_RTN_TYPE
AND 
	DR.SEQ = TRG.SHOP_RTN_SEQ
WHERE
	DR.STRR_ID = :brandCd
AND
	DR.SEASON = :season
AND
	DR.TYPE = :type
AND
	DR.SEQ = :jobSeq
GROUP BY
	DR.SEQ, DR.ITEM_CD, DR.BARCODE1, DR.BARCODE2, DR.ITEM_GCD