SELECT 
	HR.STRR_ID AS BRAND_CD
	, HR.SEASON AS SEASON_CD
	, HR.DATE_FROM, HR.DATE_TO 
	, HR.SEQ AS JOB_SEQ 
	, HR.SRC_REMARK AS MESSAGE
	, HR.STRR_ID || '-' || HR.SEASON || '-' || HR.TYPE || '-' || HR.SEQ AS WMS_BATCH_NO
	, HR.STRR_ID || '-' || HR.SEASON || '-' || HR.TYPE || '-' || HR.SEQ AS WCS_BATCH_NO
	, 'FnF' AS COM_CD
	, 'A' AS AREA_CD
	, 'A-B1' AS STAGE_CD
	, 'SRTN' AS JOB_TYPE
	, 'SORTER' AS EQUIP_TYPE
	, :equipCd AS EQUIP_CD
	, COUNT(DISTINCT DR.ITEM_CD) AS TOTAL_ORDERS
	, SUM(TRG.INB_ECT_QTY) AS TOTAL_PCS
	, SUM(1) AS TOTAL_RECORDS
	, 'order' AS ITEM_TYPE
	, 'W' AS STATUS
	, 0 AS SKIP_FLAG
FROM 
	WCS_RTN_CHASU HR 
LEFT OUTER JOIN 
	WCS_RTN_CHASU_SKU DR 
ON 
	HR.STRR_ID = DR.STRR_ID
AND
	HR.SEASON = DR.SEASON
AND
	HR.TYPE = DR.TYPE
AND
	HR.SEQ = DR.SEQ
LEFT OUTER JOIN
	(SELECT * FROM WMT_UIF_IMP_INB_RTN_TRG WHERE IF_CHK = 'N' AND WCS_IF_CHK = 'N') TRG
ON
	DR.ITEM_CD = TRG.REF_DETL_NO
AND
	HR.STRR_ID = TRG.STRR_ID
AND 
	HR.SEASON = TRG.REF_SEASON 
AND 
	HR.TYPE = TRG.SHOP_RTN_TYPE
AND 
	HR.SEQ = TRG.SHOP_RTN_SEQ
WHERE
	DATE_FROM <= :jobDate AND DATE_TO >= :jobDate
AND
	HR.STRR_ID || '-' || HR.SEASON || '-' || HR.TYPE || '-' || HR.SEQ NOT IN ( :batchId )
GROUP BY
	HR.STRR_ID, HR.SEASON, HR.TYPE, HR.SEQ, HR.DATE_FROM, HR.DATE_TO, HR.SRC_REMARK