SELECT 
	HR.STRR_ID AS BRAND_CD
	, HR.SEASON AS SEASON_CD
	, HR.DATE_FROM, HR.DATE_TO 
	, HR.SEQ AS JOB_SEQ 
	, HR.SRC_REMARK AS MESSAGE
	, HR.STRR_ID || '-' || HR.SEASON || '-' || HR.TYPE || '-' || HR.SEQ AS WMS_BATCH_NO
	, HR.STRR_ID || '-' || HR.SEASON || '-' || HR.TYPE || '-' || HR.SEQ AS WCS_BATCH_NO
	, 'FnF' AS COM_CD
	, 'A' AS AREA_CD
	, 'AB1' AS STAGE_CD
	, 'SRTN' AS JOB_TYPE
	, 'SORTER' AS EQUIP_TYPE
	, 'MHE_NO COLUMN' AS EQUIP_CD
	, COUNT(DISTINCT DR.ITEM_CD) AS TOTAL_ORDERS
	, SUM(DR.EXP_QTY) AS TOTAL_PCS
	, SUM(1) AS TOTAL_RECORDS
	, 'order' AS ITEM_TYPE
	, 'W' AS STATUS
	, 0 AS SKIP_FLAG
FROM 
	WCS_RTN_CHASU HR 
LEFT OUTER JOIN 
	WCS_RTN_CHASU_SKU DR 
ON 
	HR.STRR_ID = DR.STRR_ID
AND
	HR.SEASON = DR.SEASON
AND
	HR.TYPE = DR.TYPE
AND
	HR.SEQ = DR.SEQ
WHERE
	HR.STATUS = 'A'
AND
	HR.WH_CD = 'A'
GROUP BY
	HR.STRR_ID, HR.SEASON, HR.TYPE, HR.SEQ, HR.DATE_FROM, HR.DATE_TO, HR.SRC_REMARK