SELECT
	RACKS.CHUTE_NO, CELLS.CELL_CD, CELLS.CLASS_CD
FROM
	CELLS
LEFT OUTER JOIN
	RACKS
ON
	CELLS.EQUIP_CD = RACKS.RACK_CD
WHERE
	RACKS.CHUTE_NO IN ( :chuteNo )
AND
	RACKS.ACTIVE_FLAG = true
AND
	CELLS.ACTIVE_FLAG = true
AND
	CELLS.CATEGORY_FLAG = true
ORDER BY 
	CELLS.CELL_SEQ, CELLS.EQUIP_CD