SELECT 
	B.REF_NO
	, B.REF_DETL_NO
	, B.INB_ECT_QTY
	, B.SUPPR_ID
	, B.SUPPR_NM
	, B.INB_ECT_DATE
FROM (
	SELECT 
		REF_NO
		, REF_DETL_NO
		, max(INTERFACE_NO) AS INTERFACE_NO 
	FROM 
		WMT_UIF_IMP_INB_RTN_TRG
	WHERE 
		STRR_ID = :strrId 
	AND 
		REF_SEASON = :season 
	AND 
		SHOP_RTN_TYPE = :rtnType 
	AND 
		SHOP_RTN_SEQ = :jobSeq
	AND 
		WCS_IF_CHK = :wcsIfChk 
	AND 
		INTERFACE_ACTION = :ifAction
	GROUP BY 
		REF_NO, REF_DETL_NO ) A
LEFT OUTER JOIN 
	WMT_UIF_IMP_INB_RTN_TRG B
ON
	A.REF_NO = B.REF_NO 
AND 
	A.REF_DETL_NO = B.REF_DETL_NO 
AND 
	A.INTERFACE_NO = B.INTERFACE_NO
AND 
	B.STRR_ID = :strrId
AND 
	B.REF_SEASON = :season 
AND 
	B.SHOP_RTN_TYPE = :rtnType 
AND 
	B.SHOP_RTN_SEQ = :jobSeq
AND 
	B.WCS_IF_CHK = :wcsIfChk 
AND 
	B.INTERFACE_ACTION = :ifAction
ORDER BY 
	B.REF_NO, B.REF_DETL_NO