SELECT
	RACKS.CHUTE_NO, count(CELLS.CELL_CD) AS CNT
FROM
	CELLS
LEFT OUTER JOIN
	RACKS
ON
	CELLS.EQUIP_CD = RACKS.RACK_CD
WHERE
	RACKS.CHUTE_NO IN ( :chuteNo )
AND
	RACKS.ACTIVE_FLAG = :activeFlag
AND
	CELLS.ACTIVE_FLAG = :activeFlag
AND
	CELLS.CATEGORY_FLAG = :categoryFlag	
AND
	(CELLS.CLASS_CD IS NULL OR CHAR_LENGTH(CELLS.CLASS_CD) = 0)
GROUP BY 
	RACKS.CHUTE_NO
ORDER BY 
	RACKS.CHUTE_NO