SELECT 
	REF_NO
	, ITEM_CD
	, INB_ECT_QTY
	, SUPPR_ID
	, SUPPR_NM
	, TO_CHAR(INB_ECT_DATE, 'YYYYMMDD') AS INB_ECT_DATE
	, STRR_ID
FROM 
	FNF_WM.WMV_UIF_WCS_INB_RTN_ECT
WHERE
	WH_CD = :whCd
AND
	STRR_ID = :strrId
AND 
	REF_SEASON = :season 
AND 
	SHOP_RTN_TYPE = :rtnType 
AND 
	SHOP_RTN_SEQ = :jobSeq
AND 
	length(ref_no) = 8
ORDER BY 
	REF_NO, ITEM_CD