SELECT 
	ORD.SKU_CD
	, ORD.SKU_BARCD
	, ORD.SKU_BARCD2
	, OPRE.SUB_EQUIP_CD 
	, OPRE.CLASS_CD 
FROM 
	ORDERS ORD
LEFT OUTER JOIN
	ORDER_PREPROCESSES OPRE
ON
	ORD.BATCH_ID = OPRE.BATCH_ID
AND
	ORD.SKU_CD = OPRE.CELL_ASSGN_CD
WHERE 
	ORD.BATCH_ID = :batchId 
AND 
	ORD.SKU_CD IN ( :skuCd )