SELECT 
	STATION_CD,
	MIN(CAST(CHUTE_NO as INTEGER)) CHUTE,
	COUNT(CHUTE_NO) CNT
FROM CHUTES
WHERE DOMAIN_ID = :domainId
  AND SORTER_CD = :sorterCd
  AND ACTIVE_FLAG = :activeFlag
  AND STATUS = :status
  AND CHUTE_NO IN ( :chuteNo )
GROUP BY 
	STATION_CD
ORDER BY
	MIN(CAST(CHUTE_NO as INTEGER))