SELECT
	JB.JOB_TYPE
	, JB.TITLE
	, A.SHOP_CNT
	, A.SKU_CNT
	, A.PCS_CNT
FROM 
	JOB_BATCHES JB
LEFT OUTER JOIN 
	(
		SELECT 
			WORK_UNIT
			, COUNT(DISTINCT SHIPTO_ID) AS SHOP_CNT
			, COUNT(DISTINCT ITEM_CD) AS SKU_CNT
			, SUM(PICK_QTY) AS PCS_CNT 
		FROM 
			MHE_DR 
		WHERE 
			WORK_UNIT = :batchId 
		GROUP BY 
			WORK_UNIT
	) A
ON
	JB.WMS_BATCH_NO = A.WORK_UNIT
WHERE 
	JB.WMS_BATCH_NO = :batchId