SELECT
	OP.BATCH_ID
	, OP.SUB_EQUIP_CD
	, DR.ITEM_CD
	, DR.BARCODE2
	, DR.SHIPTO_ID
	, DR.SHIPTO_NM
	, DR.PICK_QTY
	, DR.STRR_ID
FROM
	MHE_DR DR
LEFT OUTER JOIN
	ORDER_PREPROCESSES OP
ON
	DR.WORK_UNIT = OP.BATCH_ID
AND
	DR.SHIPTO_ID = OP.CELL_ASSGN_CD
WHERE
	DR.WORK_UNIT = :batchId
AND
	OP.BATCH_ID = :batchId