SELECT 
	A.CHUTE_NO
	, A.CELL_CD
	, COALESCE(B.CELL_ASSGN_CD, '') AS SKU_CD
	, COALESCE(B.CELL_ASSGN_NM, '') AS SKU_NM
	, COALESCE(B.TOTAL_PCS, 0) AS QTY 
FROM (
	SELECT
		RACKS.CHUTE_NO
		, CELLS.CELL_CD
		, CELLS.CLASS_CD
	FROM
		CELLS
	LEFT OUTER JOIN
		RACKS
	ON
		CELLS.EQUIP_CD = RACKS.RACK_CD
	WHERE
		RACKS.CHUTE_NO = :chuteNo
	AND
		RACKS.ACTIVE_FLAG = true
	AND
		CELLS.ACTIVE_FLAG = true
	AND
		(CELLS.CLASS_CD IS NULL OR CHAR_LENGTH(CELLS.CLASS_CD) = 0)
	ORDER BY 
		CELLS.CELL_SEQ, CELLS.EQUIP_CD
) A
	LEFT OUTER JOIN
	(
	SELECT 
		* 
	FROM 
		ORDER_PREPROCESSES 
	WHERE 
		BATCH_ID = :batchId
	) B
ON
	A.CELL_CD = B.CLASS_CD
ORDER BY 
	A.CELL_CD