SELECT
	X.WORK_UNIT AS BATCH_ID,
	X.REF_NO AS ORDER_NO,
	'FnF' AS COM_CD,
	X.ITEM_CD AS SKU_CD,
	X.ORDER_QTY AS ORDER_QTY
FROM (
	SELECT
		WORK_UNIT,
		REF_NO,
		ITEM_CD,
		SUM(PICK_QTY) AS ORDER_QTY
	FROM
		MHE_DR
	WHERE
		WORK_UNIT = :batchId
		AND ITEM_CD = :skuCd
		AND (DPS_ASSIGN_YN IS NULL OR DPS_ASSIGN_YN = 'N')
		#if($skipOrderIdList)
		AND REF_NO NOT IN (:skipOrderIdList)
		#end
	GROUP BY 
		WORK_UNIT,
		REF_NO,
		ITEM_CD
) X
WHERE 
	X.ORDER_QTY <= :stockQty
ORDER BY
	ORDER_QTY ASC