SELECT
	:batchId AS BATCH_ID
	, WORK_UNIT AS WMS_BATCH_NO
	, WAVE_NO AS WCS_BATCH_NO
	, WORK_DATE AS JOB_DATE
	, WORKSEQ_NO AS JOB_SEQ
	, :jobType AS JOB_TYPE
	, WORK_DATE AS ORDER_DATE
	, REF_NO AS ORDER_NO
	, :orderLineNo AS ORDER_LINE_NO
	, :comCd AS COM_CD
	, :areaCd AS AREA_CD
	, :stageCd AS STAGE_CD
	, :equipType AS EQUIP_TYPE
	, SHIPTO_ID AS SHOP_CD
	, SHIPTO_NM AS SHOP_NM
	, ITEM_CD AS SKU_CD
	, BARCODE AS SKU_BARCD
	, ITEM_NM AS SKU_NM
	, PICK_QTY AS ORDER_QTY
FROM
	MHE_DR
WHERE
	WH_CD = :wh_cd
AND 
	WORK_UNIT = :work_unit